services:
  - type: web
    name: portfolio-backend
    runtime: python
    rootDir: backend
    buildCommand: poetry install --no-dev
    startCommand: poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
